package com.mobdeve.s15.mco.foodpad

enum class IntentKeys {
    ACCOUNT_KEY, EMAIL_KEY, USERNAME_KEY, FOLLOWER_COUNT_KEY,
    BIO_KEY, FOLLOWERS_KEY, FOLLOWING_KEY, UID_KEY, PROFILE_URI_KEY,
    IS_GOOGLE_SIGNIN_KEY,
}